server:
  port: 8080
  servlet:
    context-path: /usermanagement-api


springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

spring:
  datasource:
    url: jdbc:h2:./UserDB;


  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect